### PR TITLE
Some more features for the new C++ interface

### PR DESCRIPTION
**Pull request by mfherbst**
In this pull request I will add new features, which I need for hooking up Bohrium with [linalgwrap](https://linalgwrap.org). Please merge #366 first, because all changes here are based on the reworked C++ interface.

Right now this is work in progress ...

### CODE REVIEW

**Comment by mfherbst** [comment]
Work completed for now.

**Comment by madsbk** [comment]
rerun ubuntu

**Comment by madsbk** [comment]
rerun ubuntu

**Comment by madsbk** [comment]
rerun mac

**Comment by omegahm** [comment]
rerun mac

**Comment by omegahm** [comment]
rerun ubuntu

**Pull request merged**
