### PR TITLE
Max threads

### PR DESCRIPTION
**Pull request by madsbk**

### CODE REVIEW

**Comment by madsbk** [comment]
rerun macOS

**Comment by madsbk** [comment]
rerun ubuntu

**Comment by dionhaefner** [comment]
Would you expect this to have a major performance impact on either OpenMP or OpenCL runs? I am currently running benchmarks for our paper, so it would be nice to know if I should wait for this to be merged.

**Comment by madsbk** [comment]
No, this should make a difference when running OpenCL on CPUs

**Pull request merged**
