### PR TITLE
Be more flexible with respect to the libcuda.so

### PR DESCRIPTION
**Pull request by mfherbst**
The current setup requires the `iibcuda.so` to be in the library path. This setup tries to find it relative to the libraries, which have been determined by `FindCUDA`.

I did not test this properly, since I do not have a CUDA setup ready, so if there are issues you spot, please let me know.

Please merge #468 first as this PR depends on the changes made in the earlier PR.

### CODE REVIEW

**Comment by mfherbst** [comment]
rerun cuda

**Comment by mfherbst** [comment]
jenkins rerun cuda

**Comment by mfherbst** [comment]
@omegahm @madsbk I am not sure whether the CUDA test really failed because of my changes, since some of the tests did succeed. How can I only rerun the CUDA tests again?

And btw any documentation about the Jenkins commands anywhere? If not I am happy to do that, but I need to know how to find out.

**Comment by madsbk** [comment]
rerun ubuntu

**Comment by omegahm** [comment]
@mfherbst You can't rerun just the CUDA tests. It's essentially two main stages. Ubuntu and MacOS. Either can be rerun with `rerun X` where `X` is `ubuntu` or `macos`. This is because we only build Bohrium once on the appropriate machine and then do OpenMP/OpenCL/CUDA tests on that one build. I'll put it on my TODO-list to write up a short piece of documentation somewhere. 📜

**Comment by mfherbst** [comment]
@omegahm :+1: Cool. Thanks for the clarification.

**Pull request merged**
