### PR TITLE
Get rid of bh_error

### PR DESCRIPTION
**Pull request by omegahm**
The VEM visualizer also went out the window. (It's not used anywhere and doesn't compile)

### CODE REVIEW

**Comment by madsbk** [comment]
The visualizer work find on my machine! 

E.g. running the shallow water on OpenMP works perfectly fine: 
```python -m bohrium benchpress/benchmarks/shallow_water/python_numpy/shallow_water.py --size=100*100*100 --visualize```

However, the OpenCL backend doesn't work. Maybe OpenCL should pass-through unknown extension methods down to the OpenMP backend?

**Comment by omegahm** [comment]
Doesn't that load the visualizer from `extmethod`? This is `vem/visualizer` which uses the old way of instantiating the stack with children and `bh_component_iface` and stuff.

**Comment by madsbk** [comment]
You are right, the VEM doesn't work :)

**Comment by omegahm** [comment]
Should we delete the other stuff in there as well then? `proxy` and `node`?

**Comment by madsbk** [comment]
Let's remove `node` and keep `proxy` :)

**Pull request merged**
