### PR TITLE
Fix randn on python 3

### PR DESCRIPTION
**Pull request by dionhaefner**
Using `bh.random.randn` on Python 3 gave

```python
>>> bh.random.randn(10, 10)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "random123.pyx", line 556, in random123.RandomState.randn
  File "random123.pyx", line 691, in random123.RandomState.standard_normal
  File "random123.pyx", line 259, in random123.RandomState.random_sample
  File "random123.pyx", line 213, in random123.RandomState.random123
  File "bhary.pyx", line 95, in bhary.fix_biclass_wrapper.inner
  File "/home/dion/.virtualenvs/veros3/lib/python3.6/site-packages/bohrium/array_manipulation.py", line 372, in reshape
    return numpy.ndarray.reshape(a, newshape, **kwargs)
TypeError: 'float' object cannot be interpreted as an integer
```

the cause being that `/` defaults to float division on Python 3.

### CODE REVIEW

**Comment by omegahm** [comment]
Could we have a test for this as well?

**Comment by dionhaefner** [comment]
I thought about it, but couldn't come up with a nice way to test the random functions. Should we just check whether the command completes and produces non-trivial output?

**Comment by madsbk** [comment]
Better than nothing. But shouldn't it be possible with a full test when using the same seed?

**Comment by dionhaefner** [comment]
What do you mean by full test? Obviously can't test it against NumPy, since that uses a different RNG, doesn't it?

**Comment by madsbk** [comment]
Ahh, you are right. NumPy uses Mersenne Twister and we use Random123. 
Then let's just check for non-trivial output as you suggest.

**Comment by dionhaefner** [comment]
Is there an easy way in the testing suite to *not* compare to NumPy?

**Comment by madsbk** [comment]
You can do something like the loop test: https://github.com/bh107/bohrium/blob/master/test/python/tests/test_loop.py#L250

Where the Bohrium run return a `res` array with zeros on success and the NumPy run always return a zeros array

**Comment by dionhaefner** [comment]
How's this? Test makes sure that all array elements are unique.

**Comment by madsbk** [comment]
Great thanks!

**Pull request merged**
